'use client'

import { useState, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Search } from 'lucide-react'
import { cn } from '@/lib/utils'
import type { Note } from '@/lib/notes/types'
import { VAULT_TABS, type VaultTab, type VaultDocument, type VaultItemKind } from '@/lib/vault/types'
import { useAssist } from '@/components/assist/AssistProvider'
import VaultAllView from './VaultAllView'
import VaultNotesView from './VaultNotesView'
import VaultFlashcardsView from './VaultFlashcardsView'
import VaultDocumentsView from './VaultDocumentsView'

export default function VaultClient() {
  const [tab, setTab]       = useState<VaultTab>('all')
  const [search, setSearch] = useState('')
  const [refreshKey, setRefreshKey] = useState(0)
  const { open: openAssist } = useAssist()

  function openFromFeed(kind: VaultItemKind) {
    setTab(kind === 'note' ? 'notes' : kind === 'flashcard' ? 'flashcards' : 'documents')
  }

  // Cards generated by Noetic Assist (now the global drawer) land in the
  // flashcards table — listen for its save event so this page's lists
  // pick them up without needing to be in the same component tree.
  useEffect(() => {
    const bump = () => setRefreshKey(k => k + 1)
    window.addEventListener('noetic:flashcards-saved', bump)
    return () => window.removeEventListener('noetic:flashcards-saved', bump)
  }, [])

  function assistNote(note: Note) {
    openAssist({ kind: 'vault-note', noteId: note.id, title: note.title || 'Başlıksız Not' })
  }

  function assistDocument(doc: VaultDocument) {
    openAssist({ kind: 'vault-document', documentId: doc.id, title: doc.name })
  }

  return (
    <div className="space-y-4">
      {/* Search */}
      <div className="relative">
        <Search className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground/50" />
        <input
          value={search}
          onChange={e => setSearch(e.target.value)}
          placeholder="Search Vault..."
          className="w-full text-sm bg-white border border-border rounded-2xl pl-10 pr-4 py-3 shadow-sm focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-300 transition-all"
        />
      </div>

      {/* Tabs */}
      <div className="flex bg-white border border-border rounded-xl p-1 gap-0.5 shadow-sm overflow-x-auto">
        {VAULT_TABS.map(({ id, label }) => (
          <button
            key={id}
            onClick={() => setTab(id)}
            className={cn(
              'relative flex-1 min-w-[84px] text-xs font-semibold py-2.5 rounded-lg transition-colors whitespace-nowrap z-10',
              tab === id ? 'text-white' : 'text-muted-foreground hover:text-gray-700',
            )}
          >
            {tab === id && (
              <motion.div
                layoutId="vault-tab"
                className="absolute inset-0 bg-indigo-600 rounded-lg"
                transition={{ type: 'spring', stiffness: 420, damping: 36 }}
              />
            )}
            <span className="relative z-10">{label}</span>
          </button>
        ))}
      </div>

      {/* Content */}
      <AnimatePresence mode="wait">
        <motion.div key={tab} initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }}>
          {tab === 'all' && (
            <VaultAllView search={search} refreshKey={refreshKey} onOpenTab={openFromFeed} />
          )}

          {tab === 'notes' && (
            <VaultNotesView search={search} refreshKey={refreshKey} onAssist={assistNote} />
          )}

          {tab === 'flashcards' && (
            <VaultFlashcardsView search={search} refreshKey={refreshKey} />
          )}

          {tab === 'documents' && (
            <VaultDocumentsView search={search} refreshKey={refreshKey} onAssist={assistDocument} />
          )}

          {tab === 'saved' && (
            <div className="space-y-6">
              <SavedSection title="Notes">
                <VaultNotesView search={search} savedOnly refreshKey={refreshKey} onAssist={assistNote} />
              </SavedSection>
              <SavedSection title="Flashcards">
                <VaultFlashcardsView search={search} savedOnly refreshKey={refreshKey} />
              </SavedSection>
              <SavedSection title="Documents">
                <VaultDocumentsView search={search} savedOnly refreshKey={refreshKey} onAssist={assistDocument} />
              </SavedSection>
            </div>
          )}
        </motion.div>
      </AnimatePresence>
    </div>
  )
}

function SavedSection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <p className="text-xs font-bold text-muted-foreground uppercase tracking-widest mb-2">{title}</p>
      {children}
    </div>
  )
}
