'use client'

import { useState, useEffect } from 'react'
import { motion } from 'framer-motion'
import { Search } from 'lucide-react'
import { cn } from '@/lib/utils'
import type { Note } from '@/lib/notes/types'
import { VAULT_TABS, type VaultTab, type VaultDocument, type VaultItemKind } from '@/lib/vault/types'
import { useAssist } from '@/components/assist/AssistProvider'
import { SectionLabel } from '@/components/ui/section-label'
import VaultAllView from './VaultAllView'
import VaultNotesView from './VaultNotesView'
import VaultFlashcardsView from './VaultFlashcardsView'
import VaultDocumentsView from './VaultDocumentsView'

export default function VaultClient() {
  const [tab, setTab]       = useState<VaultTab>('all')
  const [search, setSearch] = useState('')
  const [refreshKey, setRefreshKey] = useState(0)
  const { open: openAssist } = useAssist()

  function openFromFeed(kind: VaultItemKind) {
    setTab(kind === 'note' ? 'notes' : kind === 'flashcard' ? 'flashcards' : 'documents')
  }

  // Cards generated by Noetic Assist (now the global drawer) land in the
  // flashcards table — listen for its save event so this page's lists
  // pick them up without needing to be in the same component tree.
  useEffect(() => {
    const bump = () => setRefreshKey(k => k + 1)
    window.addEventListener('noetic:flashcards-saved', bump)
    return () => window.removeEventListener('noetic:flashcards-saved', bump)
  }, [])

  function assistNote(note: Note) {
    openAssist({ kind: 'vault-note', noteId: note.id, title: note.title || 'Başlıksız Not' })
  }

  function assistDocument(doc: VaultDocument) {
    openAssist({ kind: 'vault-document', documentId: doc.id, title: doc.name })
  }

  return (
    <div className="flex flex-col md:flex-row gap-6 md:gap-10">
      {/* Collections — a plain list on the left (a scrollable row on small screens) */}
      <nav aria-label="Vault koleksiyonları" className="md:w-[200px] md:shrink-0">
        <SectionLabel className="hidden md:block mb-2 px-3">COLLECTIONS</SectionLabel>
        <ul className="flex md:flex-col gap-1 md:gap-0.5 overflow-x-auto -mx-1 px-1 md:mx-0 md:px-0">
          {VAULT_TABS.map(({ id, label }) => {
            const active = tab === id
            return (
              <li key={id} className="shrink-0">
                <button
                  onClick={() => setTab(id)}
                  aria-current={active ? 'page' : undefined}
                  className={cn(
                    'relative w-full text-left h-8 px-3 rounded-md text-base font-medium transition-colors duration-[160ms] whitespace-nowrap',
                    active ? 'text-accent' : 'text-text-secondary hover:text-text hover:bg-surface-subtle',
                  )}
                >
                  {active && <span aria-hidden className="absolute left-0 top-1.5 bottom-1.5 w-0.5 rounded-full bg-accent" />}
                  {label}
                </button>
              </li>
            )
          })}
        </ul>
      </nav>

      <div className="flex-1 min-w-0">
        {/* Search */}
        <div className="relative">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 size-4 text-text-muted" />
          <input
            value={search}
            onChange={e => setSearch(e.target.value)}
            placeholder="Search Vault…"
            aria-label="Vault içinde ara"
            className="w-full h-10 rounded-md bg-surface border border-border pl-9 pr-3 text-base text-text placeholder:text-text-muted focus:outline-none focus:border-accent transition-colors duration-[160ms]"
          />
        </div>

        {/* Content — enter-only fade so a collection never waits on the previous one's exit */}
        <motion.div
          key={tab}
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.12 }}
          className="mt-6"
        >
          {tab === 'all' && (
            <VaultAllView search={search} refreshKey={refreshKey} onOpenTab={openFromFeed} />
          )}

          {tab === 'notes' && (
            <VaultNotesView search={search} refreshKey={refreshKey} onAssist={assistNote} />
          )}

          {tab === 'flashcards' && (
            <VaultFlashcardsView search={search} refreshKey={refreshKey} />
          )}

          {tab === 'documents' && (
            <VaultDocumentsView search={search} refreshKey={refreshKey} onAssist={assistDocument} />
          )}

          {tab === 'saved' && (
            <div className="space-y-10">
              <SavedSection title="NOTES">
                <VaultNotesView search={search} savedOnly refreshKey={refreshKey} onAssist={assistNote} />
              </SavedSection>
              <SavedSection title="FLASHCARDS">
                <VaultFlashcardsView search={search} savedOnly refreshKey={refreshKey} />
              </SavedSection>
              <SavedSection title="DOCUMENTS">
                <VaultDocumentsView search={search} savedOnly refreshKey={refreshKey} onAssist={assistDocument} />
              </SavedSection>
            </div>
          )}
        </motion.div>
      </div>
    </div>
  )
}

function SavedSection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <SectionLabel className="mb-3">{title}</SectionLabel>
      {children}
    </section>
  )
}
