'use client'

import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Search } from 'lucide-react'
import { cn } from '@/lib/utils'
import type { Note } from '@/lib/notes/types'
import {
  VAULT_TABS,
  type VaultTab, type VaultDocument, type VaultItemKind, type AssistSource,
} from '@/lib/vault/types'
import VaultAllView from './VaultAllView'
import VaultNotesView from './VaultNotesView'
import VaultFlashcardsView from './VaultFlashcardsView'
import VaultDocumentsView from './VaultDocumentsView'
import NoeticAssist from './NoeticAssist'

interface AssistTarget {
  source: AssistSource
  id:     string
  title:  string
}

export default function VaultClient() {
  const [tab, setTab]       = useState<VaultTab>('all')
  const [search, setSearch] = useState('')
  const [assist, setAssist] = useState<AssistTarget | null>(null)
  const [refreshKey, setRefreshKey] = useState(0)

  function openFromFeed(kind: VaultItemKind) {
    setTab(kind === 'note' ? 'notes' : kind === 'flashcard' ? 'flashcards' : 'documents')
  }

  // Cards generated by Assist land in the flashcards table — force the
  // other views to refetch so the new cards show up immediately.
  const bumpRefresh = () => setRefreshKey(k => k + 1)

  return (
    <div className="flex flex-col lg:flex-row gap-4 items-start">
      <div className="flex-1 min-w-0 space-y-4 w-full">
        {/* Search */}
        <div className="relative">
          <Search className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground/50" />
          <input
            value={search}
            onChange={e => setSearch(e.target.value)}
            placeholder="Search Vault..."
            className="w-full text-sm bg-white border border-border rounded-2xl pl-10 pr-4 py-3 shadow-sm focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-300 transition-all"
          />
        </div>

        {/* Tabs */}
        <div className="flex bg-white border border-border rounded-xl p-1 gap-0.5 shadow-sm overflow-x-auto">
          {VAULT_TABS.map(({ id, label }) => (
            <button
              key={id}
              onClick={() => setTab(id)}
              className={cn(
                'relative flex-1 min-w-[84px] text-xs font-semibold py-2.5 rounded-lg transition-colors whitespace-nowrap z-10',
                tab === id ? 'text-white' : 'text-muted-foreground hover:text-gray-700',
              )}
            >
              {tab === id && (
                <motion.div
                  layoutId="vault-tab"
                  className="absolute inset-0 bg-indigo-600 rounded-lg"
                  transition={{ type: 'spring', stiffness: 420, damping: 36 }}
                />
              )}
              <span className="relative z-10">{label}</span>
            </button>
          ))}
        </div>

        {/* Content */}
        <AnimatePresence mode="wait">
          <motion.div key={tab} initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }}>
            {tab === 'all' && (
              <VaultAllView search={search} refreshKey={refreshKey} onOpenTab={openFromFeed} />
            )}

            {tab === 'notes' && (
              <VaultNotesView
                search={search}
                refreshKey={refreshKey}
                onAssist={(note: Note) => setAssist({
                  source: 'note', id: note.id, title: note.title || 'Başlıksız Not',
                })}
              />
            )}

            {tab === 'flashcards' && (
              <VaultFlashcardsView search={search} refreshKey={refreshKey} />
            )}

            {tab === 'documents' && (
              <VaultDocumentsView
                search={search}
                refreshKey={refreshKey}
                onAssist={(doc: VaultDocument) => setAssist({
                  source: 'document', id: doc.id, title: doc.name,
                })}
              />
            )}

            {tab === 'saved' && (
              <div className="space-y-6">
                <SavedSection title="Notes">
                  <VaultNotesView
                    search={search} savedOnly refreshKey={refreshKey}
                    onAssist={(note: Note) => setAssist({
                      source: 'note', id: note.id, title: note.title || 'Başlıksız Not',
                    })}
                  />
                </SavedSection>
                <SavedSection title="Flashcards">
                  <VaultFlashcardsView search={search} savedOnly refreshKey={refreshKey} />
                </SavedSection>
                <SavedSection title="Documents">
                  <VaultDocumentsView
                    search={search} savedOnly refreshKey={refreshKey}
                    onAssist={(doc: VaultDocument) => setAssist({
                      source: 'document', id: doc.id, title: doc.name,
                    })}
                  />
                </SavedSection>
              </div>
            )}
          </motion.div>
        </AnimatePresence>
      </div>

      {/* Noetic Assist side panel */}
      <AnimatePresence>
        {assist && (
          <NoeticAssist
            key={`${assist.source}-${assist.id}`}
            source={assist.source}
            id={assist.id}
            title={assist.title}
            onClose={() => setAssist(null)}
            onFlashcardsSaved={bumpRefresh}
          />
        )}
      </AnimatePresence>
    </div>
  )
}

function SavedSection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <p className="text-xs font-bold text-muted-foreground uppercase tracking-widest mb-2">{title}</p>
      {children}
    </div>
  )
}
